### ISSUE TITLE
ubuntu instance cloud-init failure: DataSourceNotFoundException: Did not find any data source, searched classes

### ISSUE THREAD

**Issue by larrymi** [cloudbase/nova-hyperv-charm#3]
I am trying to ssh into a ubuntu instance that I deployed with cloud image for trusty.  It is connected to admin-net network which is a private network. I had previously added ICMP ingress rule and SSH ingress rule to the security group that I am using and added my ssh keys. Also, after deploying the instance, I associate a Floating IP from external network, ext-net, so that I am able to reach the instance. However, upon trying to connect to instance, I get an error that the connection was closed.

Looking at the console logs, I see this error:
- Stopping System V runlevel compatibility^[[74G[ OK ]^M^M
  Can not apply stage final, no datasource found! Likely bad things to come!^M
  ------------------------------------------------------------^M
  Traceback (most recent call last):^M
  File "/usr/bin/cloud-init", line 318, in main_modules^M
    init.fetch()^M
  File "/usr/lib/python2.7/dist-packages/cloudinit/stages.py", line 308, in fetch^M
    return self._get_data_source()^M
  File "/usr/lib/python2.7/dist-packages/cloudinit/stages.py", line 236, in _get_data_source^M
    pkg_list)^M
  File "/usr/lib/python2.7/dist-packages/cloudinit/sources/__init__.py", line 263, in find_source^M
    raise DataSourceNotFoundException(msg)^M
  DataSourceNotFoundException: Did not find any data source, searched classes: ()^M
  ------------------------------------------------------------^M
  ^M^M

**Comment by ionutbalutoiu** [comment]
Hello,

This happens if you're using the Ubuntu VHDs downloaded from cloud-images, which judging by his description (**HyperV images for use with Microsoft Azure or SCVMM**) might not be OpenStack compatible.

If you download the qcow2 image, convert it to vhdx and use that, everything is fine.

Ionut

**Comment by larrymi** [comment]
Thanks Ionut. It does work with the qcow2 image converted to vhdx. I have opened https://bugs.launchpad.net/cloud-images/+bug/1634524 to follow up on the image issue.
