### ISSUE TITLE
Instance creation fails - Unable to connect to neutron with num-units set to 2 for nova-hyperv

### ISSUE THREAD

**Issue by larrymi** [cloudbase/nova-hyperv-charm#4]
When testing with latest version of the charm cs:~cloudbaseit/nova-hyperv-25 with num-units=2 and with Mitaka, instance creation fails with "Unable to connect to neutron pop-up errors as shown in attachment."

There was a single instance that worked but subsequent ones all gives an error. The same tests work with num-units=1

[logs-nova-hyperv.tar.gz](https://github.com/cloudbase/nova-hyperv-charm/files/566426/logs-nova-hyperv.tar.gz)

![image](https://cloud.githubusercontent.com/assets/13599808/19927582/5845fda4-a0c8-11e6-800d-675425da0544.png)

**Comment by ionutbalutoiu** [comment]
Hello Larry,

We are replicating your problem to find out the issue. I will get back to you with an answer as soon as possible.

Thank-you,
Ionut

**Comment by ionutbalutoiu** [comment]
Hello,

Please try the new version of the charm **cs:~cloudbaseit/nova-hyperv-28** and let us know if you still have this issue.

Thank-you,
Ionut

**Comment by larrymi** [comment]
Thanks Ionut! I verified that this issue has been resolved with cs:~cloudbaseit/nova-hyperv-28 version of the charm. I also verified network connectivity between instances running in separate host aggregates that each include one of the nova-hyperv unit.

![screenshot from 2016-11-07 16-16-51](https://cloud.githubusercontent.com/assets/13599808/20078316/a9d92970-a505-11e6-92a8-618fb68eca8a.png)
